### ISSUE TITLE
Image files

### ISSUE THREAD

**Issue by trhumphries** [microsoft/vssnapshotdebugger-docker#12]
Why not just add image files with snapshot debugger already installed to the container repo for .Net?

**Comment by jander-msft** [comment]
Thank you for your feedback. At this time, we are unlikely to add the Visual Studio Snapshot Debugger package and the Visual Studio Debugger (vsdbg) package to the base dotnet Docker images. We evaluate the best way to integrate these technologies on a regular basis and will update this repository to reflect the current solution when that changes.
