### ISSUE TITLE
Cannot see snapshot debugger button

### ISSUE THREAD

**Issue by hasan-hasanov** [microsoft/vssnapshotdebugger-docker#7]
Hi All,

Recently in our company we have decided to use Application Insights to log our requests and responses. We would really like to use the new Snapshot Debugger functionality. Unforutnately I cannot make it work in linux containers.

Here are the steps that I have been through:
- First I have created a base image from your repository like below

```
FROM microsoft/dotnet:2.2-aspnetcore-runtime-stretch-slim

# Install Visual Studio Snapshot Debugger prerequisites
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl libxml2 uuid libunwind8

# Install Visual Studio Snapshot Debugger
ARG VSSNAPSHOTDEBUGGER_VERSION=2.0.8
ARG VSSNAPSHOTDEBUGGER_SHA512=18cc72ca2bdb291fb126b11ec705e270ad11e0b053010afb19d0252d3f2911a02af7496adf89eec883b9183771867b234902db6a02926ad1f0f736cba5e71e77
RUN curl -SL --output vssnapshotdebugger.tar.gz "https://aka.ms/vssnapshotdebugger/release/${VSSNAPSHOTDEBUGGER_VERSION}/vssnapshotdebugger-${VSSNAPSHOTDEBUGGER_VERSION}-linux-x64.tar.gz" \
    && echo "${VSSNAPSHOTDEBUGGER_SHA512}  vssnapshotdebugger.tar.gz" | sha512sum -c - \
    && mkdir -p /diag \
    && mkdir -p /tmp/diag \
    && tar -pzxf vssnapshotdebugger.tar.gz -C /diag \
    && rm vssnapshotdebugger.tar.gz

# Set environment variables to load Visual Studio Snapshot Debugger into .NET Core applications
ENV CORECLR_ENABLE_PROFILING=1
ENV CORECLR_PROFILER={324F817A-7420-4E6D-B3C1-143FBED6D855}
ENV CORECLR_PROFILER_PATH_64=/diag/Instrumentation64/libInstrumentationEngine.so
ENV MicrosoftInstrumentationEngine_Host={CA487940-57D2-10BF-11B2-A3AD5A13CBC0}
ENV MicrosoftInstrumentationEngine_HostPath_64=/diag/Instrumentation64/libMicrosoftExtensionsHost.so
ENV MicrosoftInstrumentationEngine_FileLog=Errors
ENV MicrosoftInstrumentationEngine_FileLogPath=/tmp/diag/log.txt

# Install Visual Studio Debugger script prerequisites
RUN apt-get install -y --no-install-recommends \
        bash unzip

# Install Visual Studio Debugger
# Check the repo's README for version compatibility with Visual Studio
RUN curl -SL --output getvsdbg.sh "https://aka.ms/getvsdbgsh" \
    && bash ./getvsdbg.sh -v vs2017u5 -l /diag/vsdbg \
    && rm getvsdbg.sh

# Remove package lists to save space; can be restored with 'apt-get update'
RUN rm -rf /var/lib/apt/lists/*
```

- Then I have dockerized my application using it as a base image. Here is the Dockerfile

```
FROM TheAboveBaseImage AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY ["AppInsightPOCReceiver/AppInsightPOCReceiver.csproj", "AppInsightPOCReceiver/"]
RUN dotnet restore "AppInsightPOCReceiver/AppInsightPOCReceiver.csproj"
COPY . .
WORKDIR "/src/AppInsightPOCReceiver"
RUN dotnet build "AppInsightPOCReceiver.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "AppInsightPOCReceiver.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "AppInsightPOCReceiver.dll"]
```

- I have added the application insight packages to my application along with Application Insights SDK. I am able to see the requests and responses correctly. The only thing missing is the Snapshot Debugger button. Here are the packages I have:

	<Project Sdk="Microsoft.NET.Sdk.Web">

	  <PropertyGroup>
		<TargetFramework>netcoreapp2.2</TargetFramework>
		<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
		<ApplicationInsightsResourceId>My Resource Id</ApplicationInsightsResourceId>
		<ApplicationInsightsAnnotationResourceId>My ApplicationInsightsAnnotationResourceId</ApplicationInsightsAnnotationResourceId>
		<UserSecretsId>My User Secret Id</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	  </PropertyGroup>

	  <ItemGroup>
		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.7.1" />
		<PackageReference Include="Microsoft.ApplicationInsights.Kubernetes" Version="1.1.0" />
		<PackageReference Include="Microsoft.ApplicationInsights.SnapshotCollector" Version="1.3.5" />
		<PackageReference Include="Microsoft.ApplicationInsights.Web" Version="2.10.0" />
		<PackageReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.7.9" />
	  </ItemGroup>

	  <ItemGroup>
		<WCFMetadata Include="Connected Services" />
	  </ItemGroup>

	</Project>

- Here is how my **Startup.cs** looks like

        public class Startup
		{
			public class MyTelemetryInitializer : ITelemetryInitializer
			{
				public void Initialize(ITelemetry telemetry)
				{
					if (string.IsNullOrEmpty(telemetry.Context.Cloud.RoleName))
					{
						//set custom role name here
						telemetry.Context.Cloud.RoleName = "AI_POC_RECEIVER_ROLE_NAME";
						telemetry.Context.Cloud.RoleInstance = "AI_POC_RECEIVER_ROLE_INSTANCE";
					}
				}
			}

			public IConfiguration Configuration { get; }

			public Startup(IConfiguration configuration, IHostingEnvironment env)
			{
				this.Configuration = new ConfigurationBuilder()
					.SetBasePath(env.ContentRootPath)
					.AddJsonFile("appsettings.json", optional: true)
					.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
					.AddEnvironmentVariables()
					.Build();
			}

			public void ConfigureServices(IServiceCollection services)
			{
				services.AddSingleton<ITelemetryInitializer, MyTelemetryInitializer>();
				services.AddApplicationInsightsKubernetesEnricher();

				services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

				services.AddSnapshotCollector(configuration =>
				{
					IConfigurationSection section = Configuration.GetSection(nameof(SnapshotCollectorConfiguration));
					if (section.Value != null)
					{
						section.Bind(configuration);
					}
				});
			}

			public void Configure(IApplicationBuilder app, IHostingEnvironment env)
			{
				if (env.IsDevelopment())
				{
					app.UseDeveloperExceptionPage();
				}
				else
				{
					app.UseHsts();
				}

				app.UseHttpsRedirection();
				app.UseMvc();
			}
		}

- And finally my appsettings.json file

		{
	  "Logging": {
		"LogLevel": {
		  "Default": "Warning"
		}
	  },
	  "AllowedHosts": "*",
	  "ApplicationInsights": {
		"InstrumentationKey": "My Instrumentation Key"
	  }
		}

Some information about our environment. 

We use Azure Kubernetes Services. I currently have 1 Linux node which hosts my containers. I can make requests and responses which I can see from Application Insights but I do not have Snapshot Debugger button. Neither do I have the text _Don't see snapshot? Troubleshoot._

I have also tried with some older versions following the documentation [HERE](https://docs.microsoft.com/en-us/azure/azure-monitor/app/snapshot-debugger-vm) but the result was the same.

Can you tell me what I am doing wrong or at least point me into the right direction?

Any help is appreciated.

Thanks in advance.

**Comment by jander-msft** [comment]
This repository is containers Dockerfiles that are meant to be used in conjunction with the Visual Studio Snapshot Debugger: https://aka.ms/snappoint

These Docker images are not compatible with the completely separate feature (with a similar name), the Application Insights Snapshot Debugger, which you've referred to at this documentation: https://docs.microsoft.com/en-us/azure/azure-monitor/app/snapshot-debugger-vm

It's my understanding (I could be wrong though) that the Application Insights Snapshot Debugger currently does not support Docker containers or Linux images (as I don't see any mention of it on the documentation).

**Comment by hasan-hasanov** [comment]
I have totally mistook what this github repo does. I thought that this is somehow connected to Application Insight Snapshot Debugging. 

Thank you for your time to clarify it to me.
I will close the issue.
